version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install Node.js Deps
          command: |
            npm install
      - run:
          name: Build App
          command: |
            npm run build
      - run:
          name: List build folder
          command: |
            ls build
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - attach_workspace:
          at: ~/
      - run:
          name: Create New S3 Bucket
          command: |
            aws cloudformation deploy \
              --template-file .circleci/bucket.yml \
              --stack-name Demo-Website-${CIRCLE_WORKFLOW_ID:0:8} \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:8}"
      - run:
          name: Upload build folder to bucket
          command: |
            aws s3 sync build s3://demo-website-${CIRCLE_WORKFLOW_ID:0:8}

workflows:
  default:
    jobs:
      - build
      - deploy:
          requires:
            - build
